version: '3.8'

# Nom du projet pour éviter les conflits
name: nextcloud

services:
  nextcloud:
    image: nextcloud:apache
    container_name: nextcloud_app
    ports:
      - "8081:80"
    environment:
      - NEXTCLOUD_ADMIN_USER=à définir
      - NEXTCLOUD_ADMIN_PASSWORD=à définir
      - MYSQL_HOST=db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud123
    volumes:
      - ./nextcloud_data:/var/www/html
      - ./config:/var/www/html/config
      - ./custom_apps:/var/www/html/custom_apps
      - ./data:/var/www/html/data
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: nextcloud_db
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud123
    volumes:
      - ./mysql_data:/var/lib/mysql
    restart: unless-stopped

# Pas besoin de volumes nommés, tout est en local